[connections.sw_dino]
dialect = "mssql"
driver = "pyodbc"
host = "SERVERGLM\\SQL2019"
database = "sw_dino"          # <--- ¡ESTE ES EL CAMBIO CLAVE!
username = "bot_erp"
password = "BotDino2026*!"

[connections.sw_dino.query]
driver = "ODBC Driver 17 for SQL Server"
TrustServerCertificate = "yes"
Encrypt = "no"
