[connections.samm_bd]
dialect = "mssql"
driver = "pyodbc"
host = "SERVERGLM\\SQL2019" # direcccion del servidor al que esta conecato, como esta local, se conecta por nombre#
database = "sw_test"
username = "bot_erp"
password = "BotDino2026*!"

[connections.samm_bd.query]
driver = "ODBC Driver 17 for SQL Server"
TrustServerCertificate = "yes"
Encrypt = "no"